name: Update Fun Fact

# Controls when the workflow will run
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
jobs:
  update_fact:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a script which updates the repository's fun fact
      - name: Run a multi-line script
        run: |
          cd $GITHUB_WORKSPACE
          FACT=$(curl -s https://raw.githubusercontent.com/assaf/dailyhi/master/facts.txt | shuf -n 1)
          sed -i "14s/.*/- ⚡ **Fun fact:** $FACT. /" README.md
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Update fun fact"
          git push
          
